### ISSUE TITLE
regex error in generated Pester test

### ISSUE THREAD

**Issue by vandma** [RedeployAB/PSScaffold#4]
Concerns v2.1.0 under Windows Server 2010, PSVersion 5.1.14409.1018

Error observed when executing a generated Pester test :

> (Get-Location).Path -match "$testsPath"
parsing "Tests\Public" - Malformed \p{X} character escape.
At line:1 char:1
+ (Get-Location).Path -match "$testsPath"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException

Likely cause :

Lines in generated test :
In previous releases

**Comment by vandma** [comment]
continued ...

generated lines in test :
**# To make test runable from project root, and from test directory itself. Do quick validation.
$testsPath = Join-Path "Tests" "Public"
if ((Get-Location).Path -match "$testsPath") {**

This yields "\Tests\Public" for $testsPath, i.e. the "\P" is not escaped and generates the regex match error

in previous releases, these lines were 
**if ((Get-Location).Path -match "\\Tests\\Public") {**
i.e. "\P" was escaped.
But, admittedly, it only worked for Windows paths :(

**Comment by larsakerlund** [comment]
Thanks for reporting this @vandma! I've fixed this in the following commit: https://github.com/RedeployAB/PSScaffold/commit/06b84b4d29ecf2d0315b983fe52c57b47c5a5fa2

**Comment by KarlGW** [comment]
@vandma this update has now been merged and published (v2.1.1).
